# Generated by Django 5.0.6 on 2024-05-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('last_email_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('OK', 'Confirmado')], default='PE', max_length=2)),
            ],
        ),
    ]
