# Generated by Django 5.0.6 on 2024-05-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockinrio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255)),
                ('header', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
